### ISSUE TITLE
Welcome!

### ISSUE THREAD

**Issue by legluondunet** [GabrielMajeri/d3d9-to-11#2]
Hello and welcome to the gaming FOSS scene! 

Your project is very interesting, I would like to try it and I have some questions:
I compiled it on Ubuntu 18.04 without problem, your project is very well documented.
First ask: I didn't understand if I have to install dxvk for your dll to work?
I installed your dll in some directx9 games and the games asked for directx 9.0c.
I used the "export RUST_LOG=d3d9=info" but no log info.
Could you give me a game your dll tested with success?
I tested with:
- Rayman origins --> black windows
- Injustice --> the game didn't launch and asked for directx 9.0c

Thank you for your help.

My config:
Ubuntu 18.04
Nvidia

**Comment by GabrielMajeri** [comment]
> I compiled it on Ubuntu 18.04 without problem, your project is very well documented.

Thank you. It is good to know the docs help.

> First ask: I didn't understand if I have to install dxvk for your dll to work?

You don't _have_ to, but it's pretty much pointless without it. The objective is to obtain better performance / more features than vanilla Wine. Without DXVK, you're getting far worse performance / less features.

> I installed your dll in some directx9 games and the games asked for directx 9.0c.

That just informs you of the D3D9 version of the game.

> export RUST_LOG=d3d9=info but no log info
> Could you give me a game your dll tested with success?

I've just started this project literally _a few days ago_. The only thing it runs successfuly right now is just some simple game launchers and stuff like that.

![Oblivion launcher showing current progress](https://user-images.githubusercontent.com/3010346/44012871-d0eb5fb8-9eca-11e8-8cd7-860dde1fbd68.png)

I will update the README to better explain this.

**Comment by GabrielMajeri** [comment]
I've mentioned in the README that there currently aren't any games which are _fully_ supported by the project. I am working on adding new features every day, and will update the readme / docs when the situation changes.
